### ISSUE TITLE
rgb() color values should be clipped

### ISSUE THREAD

**Issue by wieslawsoltes** [svg-net/SVG#795]
#### Description

`
Values outside the device gamut should be clipped: the red, green, and blue values must be changed to fall within the range supported by the device. For a typical CRT monitor, whose device gamut is the same as sRGB, the three rules below are equivalent:
`

https://www.w3.org/TR/2008/REC-CSS2-20080411/syndata.html#color-units
#### Example data

```css
EM { color: rgb(300,0,0) }       /* clipped to rgb(255,0,0) */
EM { color: rgb(255,-10,0) }     /* clipped to rgb(255,0,0) */
EM { color: rgb(110%, 0%, 0%) }  /* clipped to rgb(100%,0%,0%) */
```
